[package]
name = "zk_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
bls12_381_plus = "0.8"
rand_core = "0.6"
ff = "0.13"
sha2 = "0.10"
bytes = "1.7"
bi_polynomial = {path = "../bi_polynomial"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"